### PR TITLE
CASH-1938 Compile librdkafka version 1.2.1

### PR DESCRIPTION
**Pull request by fred-jan**
~I used a newer version of the library (1.6.0) than currently runs at TRUE (1.2.1). Do we want to match that version, or are we ok to be a little ahead on that one?~ Edit: changed it to v1.2.1.

Furthermore I also bumped the version of the PHP extension from 3.1.0 to 5.0.0 in order to be compatible with the updated library (which matches the TRUE version).

### CODE REVIEW

**Comment by frankverhoeven** [comment]
> I used a newer version of the library (1.6.0) than currently runs at TRUE (1.2.1). Do we want to match that version, or are we ok to be a little ahead on that one? Edit: changed it to v1.2.1.

We could use the newer version in the 7.4 image, and stick to 1.2 in  the 7.2 image? That way we have a True compatible version in all services hosted there, and we don't use an old version in K8 services

**Comment by fred-jan** [comment]
> We could use the newer version in the 7.4 image, and stick to 1.2 in the 7.2 image?

I'm fine with that, how about you @MyOnlineStore/csi?

**Comment by tmakel** [comment]
> We could use the newer version in the 7.4 image, and stick to 1.2 in the 7.2 image?

Seems like a reasonable thought by me.

**Comment by fred-jan** [comment]
> Seems like a reasonable thought by me.

Has been adjusted.

**Comment by fred-jan** [comment]
@MyOnlineStore/csi Could you disable the CI for the no longer supported fpm-7.0 and fpm-7.1 images?

**Comment by steven166** [comment]
> @MyOnlineStore/csi Could you disable the CI for the no longer supported fpm-7.0 and fpm-7.1 images?

I've disabled the builds, unfortunately those checks cannot become green anymore. So I would suggest to just merge it :-)

**Comment by fred-jan** [comment]
> I've disabled the builds, unfortunately those checks cannot become green anymore. So I would suggest to just merge it :-)

Alright thanks, will do after someone approves it :crossed_fingers: :laughing:

**Review by frankverhoeven — APPROVED** [review]

**Pull request merged**
